FROM debian
RUN apt-get update -y -qq \
    && apt-get install -y -qq biber texlive-base texlive-bibtex-extra texlive-binaries \
    texlive-extra-utils texlive-font-utils texlive-fonts-extra-links texlive-fonts-extra \
    texlive-fonts-recommended texlive-formats-extra texlive-generic-extra texlive-generic-recommended \
    texlive-humanities texlive-lang-english texlive-lang-european texlive-lang-german texlive-latex-base \
    texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-metapost texlive-omega \
    texlive-pictures texlive-plain-extra texlive-plain-generic texlive-pstricks texlive-publishers texlive-science \
    latexmk

WORKDIR /sources/
